spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_pricing?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:20010

server:
  port: 8083
  servlet:
    context-path: /movie-master-api
logging:
  file:
    name: D:/Development/WS/log/local/movie-pricing-api/movie-pricing-api.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.example.movie.master: INFO
    org.springframework.web: TRACE

kafka:
  movieBookingApi:
    groupName: movie-schedule
    makePayment:
      topic:
        request: make-payment
    calculatePrice:
      topic:
        request: calculate-price
        serialization-class: org.example.movie.core.common.booking.BookingInformation